maes_solidarias/donations/urls.py
from django.urls import path
from .views import donation_view

app_name = 'donations'

urlpatterns = [
    path('doar/', donation_view, name='doar'),
]

maes_solidarias/maes_solidarias/urls.py
from django.contrib import admin
from django.urls import path, include 


urlpatterns = [

    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('',include('ong.urls')),
    path('donations/', include('donations.urls')),
    path('loja/', include('loja.urls')),
]

maes_solidarias/ong/urls.py
from django.urls import path

from . import views

urlpatterns = [

    path('' , views.home, name='home'),
    path('add_campanha/', views.add_campanha, name='add_campanha'),
    path('add_evento/', views.add_evento, name='add_evento'),
    path('natal/', views.natal, name='natal'),
    path('pascoa/', views.pascoa, name='pascoa'),
    path('inverno/', views.inverno, name='inverno'),
    path('dia-das-criancas/', views.criancas, name='criancas'),
]

maes_solidarias/donations/models.py
from django.db import models

class Donation(models.Model):
    
    AMOUNT_CHOICES = [
        (20, 'R$ 20'),
        (50, 'R$ 50'),
        (100, 'R$ 100'),
        ('outro', 'Outro'),
        # Adicione mais opções conforme necessário
    ]
    
    PERIODICITY_CHOICES = [
        ('U', 'Única'),
        ('M', 'Mensal'),
        # Adicione mais opções conforme necessário
    ]

    name = models.CharField(max_length=255, verbose_name='Nome')
    email = models.EmailField(verbose_name='Email')
    phone_number = models.CharField(max_length=15, verbose_name='Telefone', blank=True, null=True)
    birth_date = models.DateField(verbose_name='Data de Nascimento', blank=True, null=True)
    cpf = models.CharField(max_length=11, verbose_name='CPF', unique=True)
    amount = models.IntegerField(choices=AMOUNT_CHOICES, verbose_name='Valor da Doação')
    periodicity = models.CharField(max_length=1, choices=PERIODICITY_CHOICES, verbose_name='Periodicidade')
    donation_date = models.DateTimeField(auto_now_add=True, verbose_name='Data da Doação', choices=AMOUNT_CHOICES)

    def __str__(self):
        return f'{self.name} - {self.amount}'

    class Meta:
        verbose_name = 'Doação'
        verbose_name_plural = 'Doações'

maes_solidarias/donations/forms.py
from django import forms
from .models import Donation

class DonationForm(forms.ModelForm):
    class Meta:
        model = Donation
        fields = ['name', 'email', 'phone_number', 'birth_date', 'cpf', 'amount', 'periodicity']
        widgets = {
            'birth_date': forms.DateInput(attrs={'type': 'date'}),
            'amount': forms.Select(),
            # 'amount': forms.RadioSelect(choices=Donation.AMOUNT_CHOICES),
            'periodicity': forms.Select(),
        }

maes_solidarias/donations/views.py
from django.shortcuts import render, redirect
from .forms import DonationForm

def donation_view(request):
    if request.method == 'POST':
        form = DonationForm(request.POST)
        if form.is_valid():
            # Processamento após o formulário ser válido
            form.save()
            return redirect('algum_lugar')  # Redireciona após processar o formulário
    else:
        form = DonationForm()

    context = {'form': form}  # Certifique-se de que isso é um dicionário
    return render(request, '../templates/donations/donate.html', context)

maes_solidarias/templates/donations/donate.html
{% load static %}
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="{% static 'donate/css/donate.css' %}">
        <title>Faça sua Doação</title>
        <link href="https://fonts.googleapis.com" rel="preconnect">
        <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js" type="text/javascript"></script>
        <script type="text/javascript">
          WebFont.load({
            google: {
              families: ["Poppins:regular,500,600"]
            }
          });
        </script>
    </head>
    {% block content %}
    <body>
        <header>
            <img src="../../static/donate/images/logo.png" alt="Logo">
            <a href="../../" class="Voltar">Voltar</a>
        </header>
    <div class="centro">
        <h2 class="title">Faça sua Doação</h2>
        <form method="post">
        {% csrf_token %}
        <div class="forms">
            {{ form.as_p }}
            <a href="{% url 'donations:doar' %}" class="fazer_doacao">Fazer uma doação</a>
        </div></div>
        </form>
    </body>
    {% endblock %}
</html>